Fix typo in Mixtral accuracy
mlcommons/inference_policies pull request #297
Opened 2024-07-01 17:13 UTC by pgmpablo157321

2024-07-01 20:31 UTC, szutenberg requested changes
The typo correction is fine but in these rules I see few discrepancies:

- OpenOrca has only train spit, there is no "GPT-4 split": _The OpenOrca dataset is a collection of augmented FLAN Collection data. Currently ~1M GPT-4 completions, and ~3.2M GPT-3.5 completions._
- we used GSM8K samples from the train split (train has 7.47k, test 1.32k)
- MBXP has only test split - no need to specify
- no need to duplicate "5k samples, max_seq_len=2048". Consider writing it in a simpler form: "curated dataset containing 5k samples from GSM8K, OpenOrca, MBXP each, max_seq_len=2048
- tokens per sample should be 145.9
- there is only one accuracy category: 99%. Reference outputs are for fp16.
- rouge scores are for OpenOrca samples only

2024-07-01 21:14 UTC, mrmhodak commented
We can merge during WG meeting 7/2.

@szutenberg : Can you create a PR for the discrepancies you found?

2024-07-02 16:03 UTC, mrmhodak approved these changes

2024-07-02 16:04 UTC, merged

2024-07-02 16:05 UTC, mrmhodak commented
@pgmpablo157321 to create PR